name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows you to trigger the workflow manually

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1.1.2  # Use a specific version for stability
        with:
          max_post_count: "4"
          feed_list: "https://medium.com/feed/@godblessnyagawa"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README with latest blog posts" || echo "No changes to commit"
          git push
